export const MOVIES_REQUEST_PENDING = 'MOVIES_REQUEST_PENDING';
export const MOVIES_REQUEST_SUCCESS = 'MOVIES_REQUEST_SUCCESS';
export const MOVIES_REQUEST_FAILED = 'MOVIES_REQUEST_FAILED';

export const COUNTRIES_REQUEST_PENDING = 'COUNTRIES_REQUEST_PENDING';
export const COUNTRIES_REQUEST_SUCCESS = 'COUNTRIES_REQUEST_SUCCESS';
export const COUNTRIES_REQUEST_FAILED = 'COUNTRIES_REQUEST_FAILED';

export const FILTER_LANGUAGE = 'FILTER_LANGUAGE';
export const FILTER_YEAR = 'FILTER_YEAR';
export const FILTER_COUNTRY = 'FILTER_COUNTRY';
export const FILTER_NAME = 'FILTER_NAME';
export const FILTER_RATING = 'FILTER_RATING';

export const ALL_YEARS = "ALL_YEARS"

